"use client";
import { useEffect, useState } from "react";
import { AuthGate } from "@/components/auth-gate";
import { useAuth } from "@/components/auth-provider";
import { Card } from "@/components/ui";
import { createCompetitionTeam, getCompetitionById, getCompetitionBySlug, registerForCompetition, submitCompetitionSolution } from "@/lib/repositories/firestore";
import type { Competition } from "@/lib/types";

export default function JoinCompetition({ params }: { params: Promise<{ id: string }> }) {
  const { user } = useAuth();
  const [competition, setCompetition] = useState<Competition | null>(null);
  const [message, setMessage] = useState("");
  useEffect(() => { params.then(({ id }) => { getCompetitionById(id).then((c) => c || getCompetitionBySlug(id)).then(setCompetition); }); }, [params]);
  async function register() { if (!user || !competition) return; await registerForCompetition(competition, user.uid); setMessage("Registered for competition."); }
  async function createTeam(formData: FormData) { if (!user || !competition) return; const team = await createCompetitionTeam({ competitionId: competition.id, name: String(formData.get("name") || ""), leader: user.uid, members: [user.uid] }); setMessage(`Team created and linked to competition. Team ID: ${team.id}`); }
  async function submit(formData: FormData) { if (!user || !competition) return; const solutionLinks = String(formData.get("solutionLinks") || "").split("\n").map((x) => x.trim()).filter(Boolean); const supportingLinks = String(formData.get("supportingLinks") || "").split("\n").map((x) => x.trim()).filter(Boolean); await submitCompetitionSolution({ competitionId: competition.id, teamId: String(formData.get("teamId") || ""), title: String(formData.get("title") || ""), description: String(formData.get("description") || ""), solutionLinks, supportingLinks, submittedBy: user.uid }); setMessage("Solution submitted for evaluation."); }
  return <AuthGate><main className="min-h-screen bg-navy px-6 py-10"><div className="mx-auto max-w-4xl"><p className="text-sm uppercase tracking-[.35em] text-blue-300">Participate</p><h1 className="mt-3 font-display text-5xl">{competition?.title || "Competition"}</h1><p className="mt-3 text-white/60">Register for the competition, form your team, and submit your solution from this workspace.</p><Card className="mt-8"><h2 className="font-display text-2xl">1. Register</h2><p className="mt-2 text-white/60">Confirm your participation before creating a team or sending a solution.</p><button onClick={register} className="mt-4 rounded-full bg-blue-400 px-5 py-3 font-semibold text-navy">Register / Participate</button></Card><Card className="mt-6"><h2 className="font-display text-2xl">2. Form Team</h2><form action={createTeam} className="mt-4 grid gap-3"><input name="name" required placeholder="Team name" className="rounded-xl border border-white/10 bg-black/30 p-3" /><button className="rounded-full bg-white px-5 py-3 font-semibold text-black">Create Team</button></form></Card><Card className="mt-6"><h2 className="font-display text-2xl">3. Submit Solution</h2><form action={submit} className="mt-4 grid gap-3"><input name="teamId" placeholder="Team ID (optional)" className="rounded-xl border border-white/10 bg-black/30 p-3" /><input name="title" required placeholder="Solution title" className="rounded-xl border border-white/10 bg-black/30 p-3" /><textarea name="description" required placeholder="Solution description" className="h-24 rounded-xl border border-white/10 bg-black/30 p-3" /><textarea name="solutionLinks" placeholder="Solution links, one per line" className="h-20 rounded-xl border border-white/10 bg-black/30 p-3" /><textarea name="supportingLinks" placeholder="Supporting links, one per line" className="h-20 rounded-xl border border-white/10 bg-black/30 p-3" /><button className="rounded-full bg-white px-5 py-3 font-semibold text-black">Submit Solution</button></form>{message && <p className="mt-3 text-white/60">{message}</p>}</Card></div></main></AuthGate>;
}
