import { addDoc, collection, deleteDoc, doc, getDoc, getDocs, increment, limit, orderBy, query, serverTimestamp, setDoc, updateDoc, where, type DocumentData, type QueryConstraint, type WithFieldValue } from "firebase/firestore";
import { cache } from "react";
import { db } from "@/lib/firebase";
import type { AdminApplication, AdminInboxItem, AuditLog, CareerApplication, CareerOpening, ChallengeReview, CollaborationRequest, CommunityPost, Competition, InternalThread, KnowledgeAsset, Notification, Organization, ProblemStatement, QuestionnaireTemplate, ResearchPost, SearchResult, SystemStats, UserProfile } from "@/lib/types";

export const COLLECTIONS = {
  users: "users", organizations: "organizations", problemStatements: "problem_statements", questionnaireTemplates: "questionnaire_templates", problemReviews: "problem_reviews", internalThreads: "internal_threads", communityPosts: "community_posts", researchPosts: "research_posts", knowledgeAssets: "knowledge_assets", competitions: "competitions", collaborationRequests: "collaboration_requests", careerOpenings: "career_openings", careerApplications: "career_applications", notifications: "notifications", adminApplications: "admin_applications", adminInbox: "admin_inbox", systemStats: "system_stats", auditLogs: "audit_logs",
  challenges: "problem_statements", challengeReviews: "problem_reviews",
} as const;
export type CollectionName = (typeof COLLECTIONS)[keyof typeof COLLECTIONS];

function withId<T>(snapshot: { id: string; data: () => DocumentData }): T { return { id: snapshot.id, ...snapshot.data() } as T; }
function ref(name: CollectionName) { return collection(db, name); }
function queryFor(name: CollectionName, constraints: QueryConstraint[] = []) { return constraints.length ? query(ref(name), ...constraints) : ref(name); }
export const listCollection = cache(async <T>(name: CollectionName, constraints: QueryConstraint[] = []) => (await getDocs(queryFor(name, constraints))).docs.map((item) => withId<T>(item)));
export async function getRecord<T>(name: CollectionName, id: string) { const snap = await getDoc(doc(db, name, id)); return snap.exists() ? withId<T>(snap) : null; }
export async function createRecord<T extends object>(name: CollectionName, data: WithFieldValue<Omit<T, "id">>) { return addDoc(ref(name), data); }
export async function updateRecord(name: CollectionName, id: string, data: Record<string, unknown>) { return updateDoc(doc(db, name, id), { ...data, updatedAt: serverTimestamp() }); }
export async function upsertRecord(name: CollectionName, id: string, data: Record<string, unknown>) { return setDoc(doc(db, name, id), data, { merge: true }); }
export async function deleteRecord(name: CollectionName, id: string) { return deleteDoc(doc(db, name, id)); }

export async function logAudit(data: Omit<AuditLog, "id" | "createdAt">) { return createRecord<AuditLog>(COLLECTIONS.auditLogs, { ...data, createdAt: serverTimestamp() } as WithFieldValue<Omit<AuditLog, "id">>); }
export async function bumpStats(field: keyof Omit<SystemStats, "id" | "lastUpdated">, by = 1) { return upsertRecord(COLLECTIONS.systemStats, "platform", { [field]: increment(by), lastUpdated: serverTimestamp() }); }
export async function routeToAdminInbox(data: Omit<AdminInboxItem, "id" | "createdAt" | "updatedAt" | "status">) { return createRecord<AdminInboxItem>(COLLECTIONS.adminInbox, { ...data, status: "open", createdAt: serverTimestamp(), updatedAt: serverTimestamp() } as WithFieldValue<Omit<AdminInboxItem, "id">>); }
export async function notifyAdmins(type: Notification["type"], title: string, message: string) { return createRecord<Notification>(COLLECTIONS.notifications, { userId: "admins", type, title, message, read: false, createdAt: serverTimestamp() } as WithFieldValue<Omit<Notification, "id">>); }

function publicConstraints(publicOnly = true) { return publicOnly ? [where("visibility", "==", "public")] : []; }
export const getProblemStatements = cache(async (maxItems = 12, publicOnly = true): Promise<ProblemStatement[]> => listCollection<ProblemStatement>(COLLECTIONS.problemStatements, [...publicConstraints(publicOnly), orderBy("createdAt", "desc"), limit(maxItems)]).catch(() => listCollection<ProblemStatement>(COLLECTIONS.problemStatements, [orderBy("createdAt", "desc"), limit(maxItems)])));
export const getChallenges = getProblemStatements;
export const getAllProblemStatements = cache(async (maxItems = 100): Promise<ProblemStatement[]> => listCollection<ProblemStatement>(COLLECTIONS.problemStatements, [orderBy("createdAt", "desc"), limit(maxItems)]));
export const getAllChallenges = getAllProblemStatements;
export const getSubmittedProblemStatements = cache(async () => listCollection<ProblemStatement>(COLLECTIONS.problemStatements, [where("status", "in", ["submitted", "under_review"]), limit(100)]));
export const getSubmittedChallenges = getSubmittedProblemStatements;
export const getProblemStatementsByOrganization = cache(async (organizationId: string, admin = false) => listCollection<ProblemStatement>(COLLECTIONS.problemStatements, [where("organizationId", "==", organizationId), ...(admin ? [] : [where("visibility", "==", "public")]), limit(100)]));
export const getChallengesByOrganization = getProblemStatementsByOrganization;
export const getOrganizations = cache(async (maxItems = 50): Promise<Organization[]> => listCollection<Organization>(COLLECTIONS.organizations, [orderBy("name", "asc"), limit(maxItems)]));
export const getUsers = cache(async (maxItems = 100): Promise<UserProfile[]> => listCollection<UserProfile>(COLLECTIONS.users, [limit(maxItems)]));
export const getPlatformStats = cache(async (): Promise<SystemStats | null> => getRecord<SystemStats>(COLLECTIONS.systemStats, "platform"));
export const getQuestionnaireTemplates = cache(async () => listCollection<QuestionnaireTemplate>(COLLECTIONS.questionnaireTemplates, [orderBy("category", "asc")]));
export async function getQuestionnaireByType(category: string) { const rows = await listCollection<QuestionnaireTemplate>(COLLECTIONS.questionnaireTemplates, [where("category", "==", category), limit(1)]); return rows[0] || null; }
export const getAdminApplications = cache(async () => listCollection<AdminApplication>(COLLECTIONS.adminApplications, [orderBy("createdAt", "desc"), limit(100)]));
export const getAdminInbox = cache(async () => listCollection<AdminInboxItem>(COLLECTIONS.adminInbox, [orderBy("createdAt", "desc"), limit(100)]));
export const getNotificationsForUser = cache(async (userId: string) => listCollection<Notification>(COLLECTIONS.notifications, [where("userId", "in", [userId, "admins"]), orderBy("createdAt", "desc"), limit(50)]).catch(() => listCollection<Notification>(COLLECTIONS.notifications, [where("userId", "==", userId), orderBy("createdAt", "desc"), limit(50)])));
export const getResearchPosts = cache(async () => listCollection<ResearchPost>(COLLECTIONS.researchPosts, [where("visibility", "==", "public"), orderBy("createdAt", "desc"), limit(100)]).catch(() => listCollection<ResearchPost>(COLLECTIONS.researchPosts, [orderBy("createdAt", "desc"), limit(100)])));
export const getKnowledgeAssets = cache(async () => listCollection<KnowledgeAsset>(COLLECTIONS.knowledgeAssets, [where("visibility", "==", "public"), orderBy("createdAt", "desc"), limit(100)]).catch(() => listCollection<KnowledgeAsset>(COLLECTIONS.knowledgeAssets, [orderBy("createdAt", "desc"), limit(100)])));
export const getCommunityPosts = cache(async () => listCollection<CommunityPost>(COLLECTIONS.communityPosts, [where("visibility", "==", "public"), orderBy("createdAt", "desc"), limit(100)]).catch(() => listCollection<CommunityPost>(COLLECTIONS.communityPosts, [orderBy("createdAt", "desc"), limit(100)])));
export const getCompetitions = cache(async () => listCollection<Competition>(COLLECTIONS.competitions, [orderBy("createdAt", "desc"), limit(100)]));
export const getInternalThreads = cache(async () => listCollection<InternalThread>(COLLECTIONS.internalThreads, [orderBy("createdAt", "desc"), limit(100)]));
export const getCareerOpenings = cache(async () => listCollection<CareerOpening>(COLLECTIONS.careerOpenings, [where("visibility", "==", "public"), orderBy("createdAt", "desc"), limit(100)]).catch(() => listCollection<CareerOpening>(COLLECTIONS.careerOpenings, [orderBy("createdAt", "desc"), limit(100)])));

export async function createProblemStatement(data: Omit<ProblemStatement, "id" | "createdAt" | "updatedAt" | "status" | "visibility">) { const created = await createRecord<ProblemStatement>(COLLECTIONS.problemStatements, { ...data, createdBy: data.createdBy || data.submittedBy, status: "submitted", visibility: "private", createdAt: serverTimestamp(), updatedAt: serverTimestamp() } as WithFieldValue<Omit<ProblemStatement, "id">>); await bumpStats("problemStatementCount"); await routeToAdminInbox({ type: "Problem Submission", title: data.title, description: data.description, sourceCollection: COLLECTIONS.problemStatements, sourceId: created.id, createdBy: data.createdBy || data.submittedBy }); await notifyAdmins("problem_submission", "New Problem Statement", data.title); return created; }
export const createChallengeFromProblem = createProblemStatement;
export async function createResearchPost(data: Omit<ResearchPost, "id" | "createdAt" | "status" | "visibility">) { const created = await createRecord<ResearchPost>(COLLECTIONS.researchPosts, { ...data, status: "submitted", visibility: "private", createdAt: serverTimestamp() } as WithFieldValue<Omit<ResearchPost, "id">>); await routeToAdminInbox({ type: "Research Submission", title: data.title, description: data.summary, sourceCollection: COLLECTIONS.researchPosts, sourceId: created.id, createdBy: data.createdBy || data.author }); await notifyAdmins("research_submission", "New Research", data.title); return created; }
export async function createCollaborationRequest(data: Omit<CollaborationRequest, "id" | "createdAt" | "updatedAt" | "status">) { const created = await createRecord<CollaborationRequest>(COLLECTIONS.collaborationRequests, { ...data, status: "submitted", createdAt: serverTimestamp(), updatedAt: serverTimestamp() } as WithFieldValue<Omit<CollaborationRequest, "id">>); await routeToAdminInbox({ type: "Collaboration Request", title: data.title, description: data.description, sourceCollection: COLLECTIONS.collaborationRequests, sourceId: created.id, createdBy: data.createdBy }); await notifyAdmins("collaboration_request", "New Collaboration Request", data.title); return created; }
export async function createCareerApplication(data: Omit<CareerApplication, "id" | "createdAt" | "status">) { const created = await createRecord<CareerApplication>(COLLECTIONS.careerApplications, { ...data, status: "submitted", createdAt: serverTimestamp() } as WithFieldValue<Omit<CareerApplication, "id">>); await routeToAdminInbox({ type: "Career Application", title: data.name, description: data.email, sourceCollection: COLLECTIONS.careerApplications, sourceId: created.id, createdBy: data.email }); await notifyAdmins("career_application", "New Career Application", data.name); return created; }
export async function createAdminApplication(data: Omit<AdminApplication, "id" | "createdAt" | "status">) { const created = await createRecord<AdminApplication>(COLLECTIONS.adminApplications, { ...data, status: "pending", createdAt: serverTimestamp() } as WithFieldValue<Omit<AdminApplication, "id">>); await upsertRecord(COLLECTIONS.users, data.userId, { role: "pending_admin", email: data.email, name: data.name, updatedAt: serverTimestamp() }); await routeToAdminInbox({ type: "Role Request", title: `Admin application: ${data.name}`, description: data.email, sourceCollection: COLLECTIONS.adminApplications, sourceId: created.id, createdBy: data.userId }); await notifyAdmins("role_request", "New Admin Applicant", data.name); return created; }
export async function reviewAdminApplication(application: AdminApplication, reviewerId: string, status: "approved" | "rejected") { await updateRecord(COLLECTIONS.adminApplications, application.id, { status, reviewedBy: reviewerId, reviewedAt: serverTimestamp() }); await updateRecord(COLLECTIONS.users, application.userId, { role: status === "approved" ? "admin" : "member" }); return logAudit({ actorId: reviewerId, action: `admin_application_${status}`, collectionName: COLLECTIONS.adminApplications, documentId: application.id }); }
export async function addChallengeReview(data: Omit<ChallengeReview, "id" | "createdAt">) { const problemStatementId = data.problemStatementId || data.challengeId || ""; const review = await createRecord<ChallengeReview>(COLLECTIONS.problemReviews, { ...data, problemStatementId, createdAt: serverTimestamp() } as WithFieldValue<Omit<ChallengeReview, "id">>); if (data.statusTo) await updateRecord(COLLECTIONS.problemStatements, problemStatementId, data.statusTo === "public" ? { status: data.statusTo, visibility: "public" } : { status: data.statusTo }); return review; }
export async function convertProblemToCompetition(problem: ProblemStatement, createdBy: string) { const created = await createRecord<Competition>(COLLECTIONS.competitions, { title: problem.title, description: problem.description || problem.problemStatement || "", sourceProblemId: problem.id, status: "draft", createdBy, createdAt: serverTimestamp() } as WithFieldValue<Omit<Competition, "id">>); await routeToAdminInbox({ type: "Competition Request", title: problem.title, description: "Converted from problem statement", sourceCollection: COLLECTIONS.competitions, sourceId: created.id, createdBy }); return created; }
export async function globalSearch(term: string): Promise<SearchResult[]> { const needle = term.toLowerCase(); const [problems, orgs, research, knowledge, community, competitions] = await Promise.all([getProblemStatements(50), getOrganizations(50), getResearchPosts(), getKnowledgeAssets(), getCommunityPosts(), getCompetitions()]); return [ ...problems.map((x) => ({ id: x.id, type: "Problem Statement", title: x.title, description: x.description, href: `/problem-statements/${x.id}`, tags: [x.category || ""] })), ...orgs.map((x) => ({ id: x.id, type: "Organization", title: x.name, description: x.description, href: `/organizations/${x.id}`, tags: [x.industry || ""] })), ...research.map((x) => ({ id: x.id, type: "Research", title: x.title, description: x.summary, href: "/research", tags: x.tags })), ...knowledge.map((x) => ({ id: x.id, type: "Knowledge", title: x.title, description: x.description, href: "/knowledge", tags: x.tags })), ...community.map((x) => ({ id: x.id, type: "Community", title: x.title, description: x.content, href: "/community", tags: x.tags })), ...competitions.map((x) => ({ id: x.id, type: "Competition", title: x.title, description: x.description, href: "/competitions", tags: [x.theme || ""] })) ].filter((x) => [x.title, x.description, ...(x.tags || [])].join(" ").toLowerCase().includes(needle)); }
