import type { Metadata } from "next";
export const metadata: Metadata = { title: "Competitions — NumSum Labs", description: "Public MSME innovation challenges linked to structured industrial problems." };
import { Suspense } from "react";
import { Button, Card } from "@/components/ui";
import { CollectionBrowser } from "@/components/collection-browser";
import { EmptyState, ErrorState, LoadingState } from "@/components/data-states";
import { getPublicCompetitions } from "@/lib/repositories/firestore";
async function CompetitionDirectory() { try { const competitions = await getPublicCompetitions(); return competitions.length === 0 ? <EmptyState message="No public competitions are open right now." /> : <CollectionBrowser placeholder="Search competitions by title, theme, industry or challenge type" items={competitions.map((c) => { const href = `/competitions/${c.slug || c.id}/join`; return { id: c.id, title: c.title, description: c.shortDescription || c.description || c.detailedDescription || "", meta: [c.theme, c.industrySegment, c.status, c.registrationDeadline && `Register by ${String(c.registrationDeadline)}`, c.submissionDeadline && `Submit by ${String(c.submissionDeadline)}`].filter(Boolean).join(" · "), tags: [c.competitionType, c.industrySegment, c.status].filter(Boolean) as string[], href, action: <Button href={href}>Participate</Button> }; })} />; } catch (error) { return <ErrorState retryHref="/competitions" message={error instanceof Error ? error.message : "Unable to load competitions."} />; } }
export default function Competitions() { return <main className="min-h-screen bg-navy px-6 py-10"><h1 className="font-display text-5xl">Competitions</h1><p className="mt-3 text-white/60">Problem-linked innovation challenges converting MSME needs into solutions, prototypes, research outputs and pilot candidates.</p><Card className="mt-6"><p className="text-sm text-white/65">Select any competition to participate, form a team, and submit your solution.</p></Card><div className="mt-8"><Suspense fallback={<LoadingState label="Loading competitions" />}><CompetitionDirectory /></Suspense></div></main>; }
