"use client";
import { useEffect, useState } from "react";
import { AuthGate } from "@/components/auth-gate";
import { useAuth } from "@/components/auth-provider";
import { Card } from "@/components/ui";
import { getBookmarksForUser, getCompetitionTeamsByUser, getProblemStatementsByCreator, getResearchByCreator } from "@/lib/repositories/firestore";
import type { Bookmark, CompetitionTeam, ProblemStatement, ResearchPost } from "@/lib/types";
function fmt(v: unknown) { return v && typeof v === "object" && "toDate" in v ? (v as { toDate: () => Date }).toDate().toLocaleDateString() : v ? new Date(v as string).toLocaleDateString() : "—"; }
function ProfileContent() { const { user, profile } = useAuth(); const [problems, setProblems] = useState<ProblemStatement[]>([]); const [research, setResearch] = useState<ResearchPost[]>([]); const [teams, setTeams] = useState<CompetitionTeam[]>([]); const [bookmarks, setBookmarks] = useState<Bookmark[]>([]); useEffect(() => { if (!user) return; Promise.all([getProblemStatementsByCreator(user.uid), getResearchByCreator(user.uid), getCompetitionTeamsByUser(user.uid), getBookmarksForUser(user.uid)]).then(([p, r, t, b]) => { setProblems(p); setResearch(r); setTeams(t); setBookmarks(b); }).catch(console.error); }, [user]); return <main className="min-h-screen bg-navy px-6 py-10"><h1 className="font-display text-5xl">My Profile</h1><div className="mt-8 grid gap-4 lg:grid-cols-3"><Card><h2 className="font-display text-2xl">Profile</h2><dl className="mt-4 space-y-3 text-sm"><dt className="text-white/40">Name</dt><dd>{profile?.name || profile?.displayName || user?.displayName || "—"}</dd><dt className="text-white/40">Email</dt><dd>{profile?.email || user?.email}</dd><dt className="text-white/40">Role</dt><dd>{profile?.role || "member"}</dd><dt className="text-white/40">Organization</dt><dd>{(profile as { organization?: string } | null)?.organization || "—"}</dd><dt className="text-white/40">Joined Date</dt><dd>{fmt(profile?.createdAt)}</dd></dl></Card><Summary title="My Problems" rows={problems.map((p) => p.title)} /><Summary title="My Research" rows={research.map((r) => r.title)} /><Summary title="My Competitions" rows={teams.map((t) => t.name)} /><Summary title="My Bookmarks" rows={bookmarks.map((b) => `${b.title || b.targetId} (${b.targetType})`)} /></div></main>; }
function Summary({ title, rows }: { title: string; rows: string[] }) { return <Card><h2 className="font-display text-2xl">{title}</h2>{rows.length ? <ul className="mt-4 space-y-2 text-sm text-blue-200">{rows.map((r, i) => <li key={`${r}-${i}`}>{r}</li>)}</ul> : <p className="mt-4 text-white/55">Nothing here yet.</p>}</Card>; }
export default function Profile() { return <AuthGate><ProfileContent /></AuthGate>; }
