"use client";
import { serverTimestamp } from "firebase/firestore";
import { useState } from "react";
import { Card } from "@/components/ui";
import { createRecord, deleteRecord, updateRecord, COLLECTIONS } from "@/lib/repositories/firestore";
import type { Challenge, Organization, UserProfile } from "@/lib/types";

type Tab = "challenges" | "organizations" | "users";
export function AdminPanel({ challenges, organizations, users }: { challenges: Challenge[]; organizations: Organization[]; users: UserProfile[] }) {
  const [tab, setTab] = useState<Tab>("challenges"); const [message, setMessage] = useState("");
  async function onSubmit(formData: FormData) {
    setMessage("Saving...");
    const id = String(formData.get("id") || "");
    const payload = Object.fromEntries(formData.entries()); delete payload.id;
    try { if (id) await updateRecord(tab, id, payload); else await createRecord(tab, { ...payload, createdAt: serverTimestamp() }); setMessage("Saved. Refresh to see the latest Firestore data."); } catch (e) { setMessage(e instanceof Error ? e.message : "Save failed."); }
  }
  const rows = tab === "challenges" ? challenges : tab === "organizations" ? organizations : users;
  return <div><div className="flex flex-wrap gap-3">{(["challenges", "organizations", "users"] as Tab[]).map((item) => <button className="rounded-full bg-white/10 px-4 py-2" key={item} onClick={() => setTab(item)}>{item}</button>)}</div><Card className="mt-6"><h2 className="font-display text-2xl">Manage {tab}</h2><form action={onSubmit} className="mt-4 grid gap-3"><input name="id" placeholder="Existing document ID for edit (leave empty to create)" className="rounded-xl border border-white/10 bg-black/30 p-3" />{tab === "challenges" && <><input name="title" placeholder="title" className="rounded-xl border border-white/10 bg-black/30 p-3" /><textarea name="description" placeholder="description" className="rounded-xl border border-white/10 bg-black/30 p-3" /><input name="category" placeholder="category" className="rounded-xl border border-white/10 bg-black/30 p-3" /><input name="status" placeholder="status" className="rounded-xl border border-white/10 bg-black/30 p-3" /><input name="organizationId" placeholder="organizationId" className="rounded-xl border border-white/10 bg-black/30 p-3" /></>}{tab === "organizations" && <><input name="name" placeholder="name" className="rounded-xl border border-white/10 bg-black/30 p-3" /><input name="industry" placeholder="industry" className="rounded-xl border border-white/10 bg-black/30 p-3" /><input name="city" placeholder="city" className="rounded-xl border border-white/10 bg-black/30 p-3" /><textarea name="description" placeholder="description" className="rounded-xl border border-white/10 bg-black/30 p-3" /><input name="website" placeholder="website" className="rounded-xl border border-white/10 bg-black/30 p-3" /><input name="status" placeholder="status" className="rounded-xl border border-white/10 bg-black/30 p-3" /></>}{tab === "users" && <><input name="displayName" placeholder="displayName" className="rounded-xl border border-white/10 bg-black/30 p-3" /><input name="email" placeholder="email" className="rounded-xl border border-white/10 bg-black/30 p-3" /><input name="role" placeholder="role" className="rounded-xl border border-white/10 bg-black/30 p-3" /><input name="status" placeholder="status" className="rounded-xl border border-white/10 bg-black/30 p-3" /></>}<button className="rounded-full bg-white px-5 py-3 font-semibold text-black">Save</button></form>{message && <p className="mt-3 text-white/60">{message}</p>}</Card><div className="mt-6 grid gap-3">{rows.map((row) => <Card key={row.id}><div className="flex items-center justify-between gap-4"><pre className="overflow-auto text-xs text-white/70">{JSON.stringify(row, null, 2)}</pre><button className="rounded-full bg-red-500/20 px-4 py-2 text-red-100" onClick={async () => { await deleteRecord(tab, row.id); setMessage("Deleted. Refresh to update list."); }}>Delete</button></div></Card>)}</div></div>;
}
