"use client";
import Link from "next/link";
import { signOut, type User } from "firebase/auth";
import { Bell, ChevronDown } from "lucide-react";
import { useState } from "react";
import { useAuth } from "@/components/auth-provider";
import { auth } from "@/lib/firebase";

function ProfileMenu({ user, isAdmin }: { user: User; isAdmin: boolean }) {
  const [open, setOpen] = useState(false);
  return <div className="relative"><button aria-expanded={open} className="flex items-center gap-2 rounded-full border border-white/10 px-3 py-2 text-sm text-white/80 transition hover:border-blue-300 focus:outline-none focus:ring-2 focus:ring-blue-200/70" onClick={() => setOpen((value) => !value)}>{user.displayName || user.email || "Profile"}<ChevronDown size={16} /></button>{open && <div className="absolute right-0 z-50 mt-3 w-56 rounded-2xl border border-white/10 bg-[#07111f] p-2 shadow-2xl"><Link className="block rounded-xl px-3 py-2 text-sm text-white/75 hover:bg-white/10 hover:text-white" href="/profile">My Profile</Link><Link className="block rounded-xl px-3 py-2 text-sm text-white/75 hover:bg-white/10 hover:text-white" href="/dashboard/problems">My Problems</Link><Link className="block rounded-xl px-3 py-2 text-sm text-white/75 hover:bg-white/10 hover:text-white" href="/dashboard/challenges">My Challenges</Link><Link className="block rounded-xl px-3 py-2 text-sm text-white/75 hover:bg-white/10 hover:text-white" href="/teams">My Teams</Link>{isAdmin && <><div className="my-2 h-px bg-white/10" /><Link className="block rounded-xl px-3 py-2 text-sm text-blue-200 hover:bg-white/10 hover:text-white" href="/admin">Admin</Link><Link className="block rounded-xl px-3 py-2 text-sm text-blue-200 hover:bg-white/10 hover:text-white" href="/admin/system-health">System Health</Link></>}<div className="my-2 h-px bg-white/10" /><Link className="block rounded-xl px-3 py-2 text-sm text-white/75 hover:bg-white/10 hover:text-white" href="/settings">Settings</Link><button className="block w-full rounded-xl px-3 py-2 text-left text-sm text-red-100 hover:bg-red-500/10" onClick={() => signOut(auth)}>Logout</button></div>}</div>;
}

export function AuthNav({ mobile = false }: { mobile?: boolean }) {
  const { user, profile, requestAuth } = useAuth();
  const isAdmin = profile?.role === "admin" || profile?.role === "super_admin";
  if (mobile) {
    return <div className="grid gap-3">{user ? <><Link className="rounded-2xl border border-white/10 bg-white/[0.04] px-4 py-3 text-white/80" href="/dashboard">Dashboard</Link><Link className="rounded-2xl border border-white/10 bg-white/[0.04] px-4 py-3 text-white/80" href="/notifications">Notifications</Link>{isAdmin && <><Link className="rounded-2xl border border-blue-300/20 bg-blue-300/10 px-4 py-3 text-blue-100" href="/admin">Admin</Link><Link className="rounded-2xl border border-blue-300/20 bg-blue-300/10 px-4 py-3 text-blue-100" href="/admin/system-health">System Health</Link></>}<button className="rounded-2xl border border-red-200/15 px-4 py-3 text-left text-red-100" onClick={() => signOut(auth)}>Logout</button></> : <><button className="rounded-2xl border border-white/10 px-4 py-3 text-left text-white/80" onClick={() => requestAuth()}>Sign in</button><Link className="rounded-2xl bg-blue-300 px-4 py-3 font-semibold text-navy" href="/join">Join as Member</Link></>}</div>;
  }
  return <div className="flex items-center gap-2">{user ? <><Link className="rounded-full px-4 py-2 text-sm text-white/75 transition hover:text-white" href="/dashboard">Dashboard</Link><Link aria-label="Notifications" className="rounded-full border border-white/10 p-2 text-white/75 transition hover:border-blue-300 hover:text-white" href="/notifications"><Bell size={18} /></Link>{isAdmin && <Link className="rounded-full border border-blue-300/20 px-3 py-2 text-xs font-semibold text-blue-100" href="/admin">Admin</Link>}<ProfileMenu user={user} isAdmin={isAdmin} /></> : <><button className="rounded-full px-4 py-2 text-sm text-white/70 transition hover:text-white" onClick={() => requestAuth()}>Sign in</button><Link className="rounded-full bg-blue-300 px-4 py-2 text-sm font-semibold text-navy shadow-glow transition hover:bg-blue-200" href="/join">Join as Member</Link></>}</div>;
}
