"use client";
import { useMemo, useState } from "react";
import { EmptyState } from "@/components/data-states";
import { Button, Card } from "@/components/ui";
import type { Challenge } from "@/lib/types";

const pageSize = 6;
function timeValue(value: Challenge["createdAt"]) { if (!value) return 0; if (typeof value === "object" && "toMillis" in value) return value.toMillis(); return new Date(value as string | number | Date).getTime() || 0; }
export function ChallengeBrowser({ challenges }: { challenges: Challenge[] }) {
  const [search, setSearch] = useState(""); const [category, setCategory] = useState(""); const [status, setStatus] = useState(""); const [sort, setSort] = useState("newest"); const [page, setPage] = useState(1);
  const categories = useMemo(() => Array.from(new Set(challenges.map((c) => c.category).filter(Boolean))), [challenges]);
  const statuses = useMemo(() => Array.from(new Set(challenges.map((c) => c.status).filter(Boolean))), [challenges]);
  const filtered = useMemo(() => challenges.filter((c) => [c.title, c.description, c.category].join(" ").toLowerCase().includes(search.toLowerCase())).filter((c) => !category || c.category === category).filter((c) => !status || c.status === status).sort((a,b) => sort === "oldest" ? timeValue(a.createdAt) - timeValue(b.createdAt) : timeValue(b.createdAt) - timeValue(a.createdAt)), [challenges, search, category, status, sort]);
  const totalPages = Math.max(1, Math.ceil(filtered.length / pageSize)); const items = filtered.slice((page - 1) * pageSize, page * pageSize);
  return <div className="grid gap-4 md:grid-cols-[280px_1fr]"><Card><h2 className="font-semibold">Filters</h2><input value={search} onChange={(e) => { setSearch(e.target.value); setPage(1); }} placeholder="Search challenges" className="mt-3 w-full rounded-xl border border-white/10 bg-black/30 p-3" /><select value={category} onChange={(e) => { setCategory(e.target.value); setPage(1); }} className="mt-3 w-full rounded-xl border border-white/10 bg-black/30 p-3"><option value="">All categories</option>{categories.map((item) => <option key={item}>{item}</option>)}</select><select value={status} onChange={(e) => { setStatus(e.target.value); setPage(1); }} className="mt-3 w-full rounded-xl border border-white/10 bg-black/30 p-3"><option value="">All statuses</option>{statuses.map((item) => <option key={item}>{item}</option>)}</select><select value={sort} onChange={(e) => setSort(e.target.value)} className="mt-3 w-full rounded-xl border border-white/10 bg-black/30 p-3"><option value="newest">Newest</option><option value="oldest">Oldest</option></select></Card><div>{items.length === 0 ? <EmptyState message="Be among the first contributors" /> : <div className="grid gap-4 md:grid-cols-2">{items.map((challenge) => <Card key={challenge.id}><p className="text-blue-300">{[challenge.category, challenge.status].filter(Boolean).join(" · ") || "Challenge"}</p><h2 className="mt-2 font-display text-2xl">{challenge.title}</h2><p className="mt-3 text-white/60">{challenge.description || "Details will be published by the organization."}</p>{challenge.organizationId && <p className="mt-4 text-xs text-white/45">Organization: {challenge.organizationId}</p>}</Card>)}</div>}<div className="mt-6 flex gap-3"><Button variant="secondary" href="#" onClick={(e) => { e.preventDefault(); setPage((p) => Math.max(1, p - 1)); }}>Previous</Button><span className="self-center text-sm text-white/60">Page {page} of {totalPages}</span><Button variant="secondary" href="#" onClick={(e) => { e.preventDefault(); setPage((p) => Math.min(totalPages, p + 1)); }}>Next</Button></div></div></div>;
}
