"use client";
import { useState } from "react";
import { useAuth, useIsAdmin } from "@/components/auth-provider";
import { Card } from "@/components/ui";
import { createKnowledgeFromWinningSolution, registerForCompetition, scoreCompetitionSubmission, submitCompetitionSolution, updateCompetitionStatus } from "@/lib/repositories/firestore";
import type { Competition, CompetitionSubmission } from "@/lib/types";

export function CompetitionActions({ competition, submissions }: { competition: Competition; submissions: CompetitionSubmission[] }) {
  const { user, requestAuth } = useAuth();
  const isAdmin = useIsAdmin();
  const [message, setMessage] = useState("");
  async function register() { if (!user) return requestAuth({ message: "Sign in to register for this competition." }); setMessage("Registering..."); await registerForCompetition(competition, user.uid); setMessage("Registration recorded."); }
  async function submit(formData: FormData) { if (!user) return requestAuth({ message: "Sign in to submit a solution." }); const solutionLinks = String(formData.get("solutionLinks") || "").split("\n").map((x) => x.trim()).filter(Boolean); const supportingLinks = String(formData.get("supportingLinks") || "").split("\n").map((x) => x.trim()).filter(Boolean); await submitCompetitionSolution({ competitionId: competition.id, teamId: String(formData.get("teamId") || ""), title: String(formData.get("title") || ""), description: String(formData.get("description") || ""), solutionLinks, supportingLinks, submittedBy: user.uid }); setMessage("Solution submitted for evaluation."); }
  async function status(status: Competition["status"], visibility: Competition["visibility"] = competition.visibility) { if (!user) return; await updateCompetitionStatus(competition, user.uid, status, visibility); setMessage(`Competition marked ${status}.`); }
  async function winner(submission: CompetitionSubmission) { if (!user) return; await scoreCompetitionSubmission(submission, user.uid, Number(submission.score || 100), 1, submission.reviewNotes || "Selected as winning solution.", true); await createKnowledgeFromWinningSolution(competition, submission, user.uid); setMessage("Winner selected and draft knowledge asset created."); }
  return <Card className="mt-6"><h2 className="font-display text-2xl">Competition Actions</h2><div className="mt-4 flex flex-wrap gap-3"><button onClick={register} className="rounded-full bg-blue-400 px-5 py-3 font-semibold text-navy">Register</button>{isAdmin && <><button onClick={() => status("active", "public")} className="rounded-full bg-green-500/20 px-4 py-2 text-green-100">Publish</button><button onClick={() => status("evaluation", competition.visibility)} className="rounded-full bg-purple-500/20 px-4 py-2 text-purple-100">Close</button><button onClick={() => status("archived", "private")} className="rounded-full bg-amber-500/20 px-4 py-2 text-amber-100">Archive</button></>}</div><form action={submit} className="mt-6 grid gap-3"><h3 className="font-semibold">Submit Solution</h3><input name="teamId" placeholder="Team ID (optional)" className="rounded-xl border border-white/10 bg-black/30 p-3" /><input name="title" required placeholder="Solution title" className="rounded-xl border border-white/10 bg-black/30 p-3" /><textarea name="description" required placeholder="Solution description" className="h-24 rounded-xl border border-white/10 bg-black/30 p-3" /><textarea name="solutionLinks" placeholder="Solution links, one per line" className="h-20 rounded-xl border border-white/10 bg-black/30 p-3" /><textarea name="supportingLinks" placeholder="Supporting links, one per line" className="h-20 rounded-xl border border-white/10 bg-black/30 p-3" /><button className="rounded-full bg-white px-5 py-3 font-semibold text-black">Submit Solution</button></form>{isAdmin && submissions.length > 0 && <div className="mt-6 grid gap-2"><h3 className="font-semibold">Evaluation</h3>{submissions.map((submission) => <button key={submission.id} onClick={() => winner(submission)} className="rounded-xl border border-white/10 bg-black/20 p-3 text-left text-blue-200">Select winner: {submission.title}</button>)}</div>}{message && <p className="mt-3 text-white/60">{message}</p>}</Card>;
}
