import type { Challenge, Questionnaire } from "./types";
export const navItems = ["Home","Challenges","MSME Intelligence","Research","Community","Competitions","Organizations","Knowledge Hub"] as const;
export const sectors = ["Manufacturing","Quality","Reliability","Energy","Automation","Digital Transformation","Supply Chain","Product Design","Sustainability","Exports","AI","Operations"];
export const skills = ["Mechanical","Electrical","Electronics","Software","AI","Data Science","Manufacturing","Quality","Business","Marketing","Finance","Design","Research","Operations"];
export const challenges: Challenge[] = [
 {id:"predictive-bearing-failure",title:"Predict bearing failures before unplanned stoppage",category:"Reliability",industry:"Manufacturing",participants:84,status:"open",difficulty:"Expert",timeline:"8 weeks",reward:"Sponsored pilot",location:"Hybrid"},
 {id:"vision-defect-detection",title:"Reduce cosmetic defect escapes on fast-moving line",category:"Quality",industry:"Automation",participants:126,status:"active",difficulty:"Advanced",timeline:"6 weeks",reward:"₹2L grant",location:"Remote"},
 {id:"energy-load-optimization",title:"Optimize peak-hour energy load for MSME cluster",category:"Energy",industry:"Operations",participants:58,status:"open",difficulty:"Advanced",timeline:"10 weeks",location:"India"}
];
export const questionnaires: Questionnaire[] = [
 {challengeType:"Reliability Problem",configurable:true,fields:[{id:"equipmentType",label:"Equipment Type",type:"text",required:true},{id:"failureFrequency",label:"Failure Frequency",type:"select",required:true,options:["Daily","Weekly","Monthly","Rare"]},{id:"downtimeCost",label:"Downtime Cost",type:"number",required:false},{id:"currentMonitoring",label:"Current Monitoring",type:"textarea",required:false},{id:"criticality",label:"Criticality",type:"select",required:true,options:["Low","Medium","High","Mission Critical"]},{id:"existingPractices",label:"Existing Practices",type:"textarea",required:false},{id:"attachments",label:"Photos, Documents, Videos",type:"file",required:false}]},
 {challengeType:"Quality Problem",configurable:true,fields:[{id:"defectType",label:"Defect Type",type:"text",required:true},{id:"inspectionMethod",label:"Inspection Method",type:"text",required:true},{id:"defectRate",label:"Defect Rate",type:"number",required:true},{id:"productionVolume",label:"Production Volume",type:"number",required:false},{id:"currentControls",label:"Current Controls",type:"textarea",required:false},{id:"attachments",label:"Attachments",type:"file",required:false}]},
 {challengeType:"Product Development Problem",configurable:true,fields:[{id:"currentProduct",label:"Current Product",type:"text",required:true},{id:"targetMarket",label:"Target Market",type:"text",required:true},{id:"customerProblem",label:"Customer Problem",type:"textarea",required:true},{id:"expectedOutcome",label:"Expected Outcome",type:"textarea",required:true},{id:"budgetRange",label:"Budget Range",type:"select",required:false,options:["Prototype","Pilot","Commercial"]},{id:"timeline",label:"Timeline",type:"text",required:false},{id:"attachments",label:"Attachments",type:"file",required:false}]}
];
