import type { Timestamp } from "firebase/firestore";

export type Role = "visitor" | "member" | "reviewer" | "moderator" | "organization" | "pending_admin" | "admin" | "super_admin";
export type PlatformStatus = "draft" | "submitted" | "under_review" | "needs_information" | "onboarded" | "structured" | "active" | "completed" | "published" | "archived" | "rejected" | "member_only" | "public" | "researching" | "competition" | "solved";
export type ContentStatus = PlatformStatus;
export type ProblemStatementStatus = ContentStatus;
export type Visibility = "admin_only" | "submitter_only" | "team_only" | "member_only" | "public" | "private";
export type ReviewAction = "comment" | "request_information" | "assign_research" | "assign_reviewer" | "change_status" | "change_visibility" | "approve_publication" | "approve" | "reject" | "assign" | "publish" | "archive" | "convert_to_competition" | "request_clarification";
export type AdminApplicationStatus = "pending" | "approved" | "rejected";
export type NotificationType = "admin_application" | "problem_submission" | "problem_review" | "research_submission" | "role_request" | "career_application" | "competition_request" | "competition_submission" | "knowledge_submission" | "collaboration_request" | "collaboration_acceptance" | "community_report" | "comment" | "reply" | "mention" | "bookmark" | "discussion_assignment" | "moderation_action" | "competition_update" | "knowledge_update";
export type KnowledgeAssetType = "Research" | "Case Study" | "Framework" | "Template" | "Guide" | "Best Practice" | "Industry Report";
export type CompetitionSourceType = "problem_statement" | "research" | "community_discussion" | "direct_admin" | "general";
export type CompetitionStatus = "draft" | "published" | "open" | "active" | "closed" | "evaluating" | "completed" | "archived";
export type KnowledgeSourceType = "problem_statement" | "research" | "competition" | "community" | "manual";
export type KnowledgeStatus = "draft" | "published" | "archived";
export type ProblemCategory = "Manufacturing" | "Reliability" | "Quality" | "Energy" | "Digital Transformation" | "Supply Chain" | "Product Development" | "Export" | "Finance" | "Other";
export type ChallengeStatus = ProblemStatementStatus;
export type ChallengeCategory = ProblemCategory;
export type DateLike = Timestamp | Date | string | number | null;
export type AdminInboxType = "problem_submission" | "research_submission" | "role_request" | "competition_request" | "career_application" | "knowledge_submission" | "community_report" | "collaboration_request";
export type AssociatedType = "problem_statement" | "research" | "competition" | "knowledge_asset" | "sop_document" | "pilot_track" | "meeting_log" | "questionnaire_response" | "constitution_document" | "objective_target_document" | "organization" | "msme_case" | "team" | "community";
export type DiscussionTargetType = AssociatedType | "general";
export type DiscussionType = "general" | "problem" | "research" | "competition" | "knowledge" | "organization" | "msme" | "team";
export type ResearchStatus = "draft" | "submitted" | "under_review" | "member_only" | "public" | "published" | "archived" | "rejected";
export type LinkedResourceType = AssociatedType | "file" | "external_link" | "onboarding_session";
export type DocumentVersionStatus = "draft" | "under_review" | "published" | "archived";
export type UserProfileType = "msme_owner" | "msme_representative" | "industrialist" | "researcher" | "student" | "engineer_professional" | "consultant" | "startup_founder" | "academic_institution_representative" | "technology_provider" | "government_incubator_association" | "investor" | "other";

export interface FirestoreEntity { id: string; }
export interface TeamMember extends FirestoreEntity { name: string; institution?: string; degree?: string; discipline?: string; designation?: string; bio?: string; photoUrl?: string; linkedinUrl?: string; displayOrder?: number; createdAt?: DateLike; updatedAt?: DateLike; }
export interface UserProfile extends FirestoreEntity { uid?: string; displayName?: string; name?: string; fullName?: string; email?: string; phoneNumber?: string; profileType?: UserProfileType; city?: string; state?: string; country?: string; shortBio?: string; professionalSummary?: string; role?: Role; status?: string; profileComplete?: boolean; profileCompletedAt?: DateLike; organizationId?: string; organizationIds?: string[]; memberModuleEnabled?: boolean; onboardingCompletedAt?: DateLike; organizationName?: string; organizationType?: string; industrySegment?: string; manufacturingOrServiceFocus?: string; productsOrServices?: string; companySize?: string; website?: string; gstOrUdyam?: string; majorChallenges?: string; institutionName?: string; departmentOrDiscipline?: string; researchInterests?: string; skills?: string[]; currentRole?: string; portfolioOrLinkedIn?: string; domainExpertise?: string; yearsOfExperience?: string; industriesWorkedWith?: string; startupOrCompanyName?: string; solutionArea?: string; targetIndustries?: string; productStage?: string; createdAt?: DateLike; updatedAt?: DateLike; }
export interface OrganizationProfile extends FirestoreEntity { name: string; publicLabel?: string; industry?: string; description?: string; website?: string; logo?: string; verificationStatus?: "unverified" | "pending" | "verified" | "rejected"; city?: string; state?: string; country?: string; status?: string; createdBy?: string; createdAt?: DateLike; updatedAt?: DateLike; }
export interface Organization extends OrganizationProfile {}
export interface LinkedResource { id?: string; type: LinkedResourceType; collection?: string; resourceId: string; title?: string; visibility?: Visibility; status?: PlatformStatus; url?: string; linkedAt?: DateLike; linkedBy?: string; }
export interface ProblemStatement extends FirestoreEntity { title: string; summary?: string; description?: string; problemDescription?: string; category?: ProblemCategory | string; questionnaireResponses?: Record<string, unknown>; attachments?: string[]; createdBy?: string; organizationType?: string; visibility?: Visibility; status?: ProblemStatementStatus; createdAt?: DateLike; updatedAt?: DateLike; organization?: string; organizationId?: string; publicOrganizationLabel?: string; problemStatement?: string; submittedBy?: string; assignedResearcher?: string; assignedReviewer?: string; questionnaire?: Record<string, unknown>; adminNotes?: string; submitterId?: string; ownerIds?: string[]; teamIds?: string[]; structuredChallengeId?: string; convertedCompetitionId?: string; linkedResources?: LinkedResource[]; publishedAt?: DateLike; }
export type Challenge = ProblemStatement;
export interface QuestionnaireQuestion { id: string; label: string; type: "text" | "textarea" | "number" | "dropdown" | "select" | "checkbox" | "radio" | "date" | "url" | "email" | "file_link"; required?: boolean; options?: string[]; placeholder?: string; }
export interface QuestionnaireTemplate extends FirestoreEntity { category: ProblemCategory | string; name?: string; questions: QuestionnaireQuestion[]; createdBy?: string; createdAt?: DateLike; updatedAt?: DateLike; }
export interface ProblemReview extends FirestoreEntity { problemStatementId: string; action: ReviewAction; comment?: string; requestedInfo?: string; assignedTo?: string; statusFrom?: ProblemStatementStatus; statusTo?: ProblemStatementStatus; visibilityFrom?: Visibility; visibilityTo?: Visibility; createdBy: string; createdAt?: DateLike; }
export type ChallengeReview = ProblemReview & { challengeId?: string };
export interface ThreadReply { id: string; body: string; author: string; mentions?: string[]; attachments?: string[]; createdAt?: DateLike; }
export interface InternalThread extends FirestoreEntity { problemStatementId?: string; challengeId?: string; title: string; body?: string; replies?: ThreadReply[]; mentions?: string[]; attachments?: string[]; auditHistory?: string[]; createdBy: string; createdAt?: DateLike; updatedAt?: DateLike; }
export interface Notification extends FirestoreEntity { userId: string; type: NotificationType; title: string; message: string; read: boolean; problemStatementId?: string; createdAt?: DateLike; }
export interface AdminApplication extends FirestoreEntity { userId: string; name: string; email: string; requestedRole?: Role; experience?: string; motivation?: string; skills?: string[]; status: AdminApplicationStatus; createdAt?: DateLike; reviewedBy?: string; reviewedAt?: DateLike; }
export interface AdminInboxComment { id: string; body: string; authorId: string; authorName?: string; createdAt?: DateLike; }
export interface AdminInboxItem extends FirestoreEntity { type: AdminInboxType; title: string; description?: string; sourceCollection: string; sourceId: string; status?: "pending" | "assigned" | "under_review" | "resolved" | "archived" | "open" | "approved" | "rejected" | "published" | "clarification_requested"; assignedTo?: string; comments?: AdminInboxComment[]; createdBy?: string; createdAt?: DateLike; updatedAt?: DateLike; }
export interface CommunityAttachment { type: "pdf" | "image" | "github" | "google_drive" | "doi" | "researchgate" | "website" | "video"; label: string; url: string; }
export interface CommunityComment { id: string; content: string; createdBy: string; createdAt?: DateLike; updatedAt?: DateLike; replies?: CommunityComment[]; likes?: string[]; bookmarks?: string[]; mentions?: string[]; reportedBy?: string[]; deleted?: boolean; }
export interface CommunityPost extends FirestoreEntity { title: string; content: string; type?: DiscussionType; linkedEntityType?: DiscussionTargetType; linkedEntityId?: string; associatedType?: DiscussionTargetType; associatedId?: string; targetType?: DiscussionTargetType; targetId?: string; problemStatementId?: string; groupId?: string; visibility?: Visibility; tags?: string[]; author: string; createdBy?: string; createdAt?: DateLike; updatedAt?: DateLike; upvotes?: string[]; bookmarks?: string[]; comments?: CommunityComment[]; status?: string; views?: number; attachments?: CommunityAttachment[]; mentions?: string[]; organization?: string; reportedBy?: string[]; }
export interface ResearchPost extends FirestoreEntity { title: string; abstract?: string; summary: string; doi?: string; researchGate?: string; github?: string; pdf?: string; seekCollaboration?: boolean; researchLink?: string; documentLinks?: string[]; supportingFolderLink?: string; problemStatementId?: string; associatedProblemId?: string; author?: string; authors?: string[]; category?: string; tags?: string[]; documentLink?: string; externalReferences?: string[]; createdBy?: string; createdAt?: DateLike; updatedAt?: DateLike; upvotes?: string[]; bookmarks?: string[]; status?: ResearchStatus; visibility?: Visibility; }
export interface KnowledgeAsset extends FirestoreEntity { title: string; description: string; summary?: string; content?: string; references?: string[]; sourceType?: KnowledgeSourceType; sourceId?: string; type?: KnowledgeAssetType; category?: string; documentLink?: string; originSource?: string; linkedProblemStatementId?: string; sourceProblemId?: string; sourceResearchId?: string; sourceCompetitionId?: string; tags?: string[]; createdBy: string; createdAt?: DateLike; status?: ContentStatus; visibility?: Visibility; }
export interface CollaborationRequest extends FirestoreEntity { title: string; description: string; requiredSkills?: string[]; expertiseRequired?: string[]; duration?: string; organization?: string; visibility?: Visibility; adminReviewRequired?: boolean; expectedContribution?: string; associatedType: AssociatedType; associatedId: string; sourceType?: AssociatedType; sourceId?: string; problemStatementId?: string; status?: ContentStatus; createdBy?: string; createdAt?: DateLike; updatedAt?: DateLike; }
export interface PrivateCollaborationGroup extends FirestoreEntity { name: string; description?: string; associatedType?: AssociatedType; associatedId?: string; associatedProblemId?: string; members?: string[]; owner?: string; admins?: string[]; messages?: Array<{ id: string; body: string; createdBy: string; createdAt?: DateLike }>; documents?: CommunityAttachment[]; activityLog?: string[]; permissions?: Record<string, string[]>; createdBy?: string; visibility: "private"; createdAt?: DateLike; updatedAt?: DateLike; }
export interface Competition extends FirestoreEntity { title: string; description: string; eligibility?: string; deadline?: DateLike; submissionFormId?: string; judges?: string[]; rewards?: string; theme?: string; sourceType?: CompetitionSourceType; sourceId?: string; sourceProblemId?: string; sourceResearchId?: string; submissionTemplate?: string; evaluationCriteria?: string; visibility?: Visibility; winnerSubmissionId?: string; winningTeamId?: string; startDate?: DateLike; endDate?: DateLike; rules?: string; prize?: string; prizes?: string; status?: CompetitionStatus; registrations?: string[]; teams?: string[]; submissions?: string[]; evaluation?: Record<string, unknown>; leaderboard?: Array<{ team: string; score: number }>; createdBy?: string; createdAt?: DateLike; updatedAt?: DateLike; }
export interface CompetitionTeam extends FirestoreEntity { competitionId: string; name: string; leader: string; members?: string[]; emails?: string[]; institute?: string; organization?: string; createdAt?: DateLike; updatedAt?: DateLike; }
export interface CompetitionSubmission extends FirestoreEntity { competitionId: string; teamId?: string; submissionType?: "individual" | "team"; proposal?: string; documents?: string[]; links?: string[]; presentation?: string; title: string; proposalTitle?: string; description: string; driveLink?: string; githubLink?: string; documentLink?: string; solutionLinks?: string[]; supportingLinks?: string[]; submittedBy: string; submittedAt?: DateLike; score?: number; rank?: number; reviewNotes?: string; winner?: boolean; evaluatedBy?: string; evaluatedAt?: DateLike; }
export interface ProblemOnboardingSession extends FirestoreEntity { problemStatementId: string; scheduledAt?: DateLike; recordedAt?: DateLike; facilitatorId?: string; participantIds?: string[]; notes?: string; meetingUrl?: string; recordingUrl?: string; questionnaireResponseId?: string; status?: PlatformStatus; visibility?: Visibility; createdBy?: string; createdAt?: DateLike; updatedAt?: DateLike; }
export interface QuestionnaireResponse extends FirestoreEntity { problemStatementId: string; templateId?: string; sessionId?: string; respondentId?: string; responses: Record<string, unknown>; status?: PlatformStatus; visibility?: Visibility; createdBy?: string; createdAt?: DateLike; updatedAt?: DateLike; }
export interface SOPDocument extends FirestoreEntity { title: string; summary?: string; content?: string; documentLink?: string; problemStatementId?: string; version?: number; status?: PlatformStatus; visibility?: Visibility; createdBy?: string; createdAt?: DateLike; updatedAt?: DateLike; }
export interface ResearchItem extends ResearchPost {}
export interface PilotTrack extends FirestoreEntity { title: string; problemStatementId: string; summary?: string; milestones?: Array<{ title: string; status?: PlatformStatus; dueAt?: DateLike }>; ownerIds?: string[]; status?: PlatformStatus; visibility?: Visibility; createdBy?: string; createdAt?: DateLike; updatedAt?: DateLike; }
export interface MeetingLog extends FirestoreEntity { title: string; problemStatementId: string; occurredAt?: DateLike; participantIds?: string[]; notes?: string; actionItems?: string[]; files?: string[]; status?: PlatformStatus; visibility?: Visibility; createdBy?: string; createdAt?: DateLike; updatedAt?: DateLike; }
export interface DiscussionPost extends CommunityPost {}
export interface DiscussionComment extends CommunityComment { postId?: string; parentCommentId?: string; }
export interface SuccessStory extends FirestoreEntity { title: string; summary: string; problemStatementId?: string; organizationId?: string; outcomeMetrics?: Record<string, unknown>; status?: PlatformStatus; visibility?: Visibility; createdBy?: string; createdAt?: DateLike; updatedAt?: DateLike; }
export interface TestimonialRating extends FirestoreEntity { title?: string; body?: string; rating?: number; problemStatementId?: string; organizationId?: string; authorId?: string; status?: PlatformStatus; visibility?: Visibility; createdAt?: DateLike; updatedAt?: DateLike; }
export interface VersionedDocumentVersion { version: number; body?: string; fileUrl?: string; amendedBy?: string; amendedAt?: DateLike; status?: DocumentVersionStatus; changeSummary?: string; }
export interface ConstitutionDocument extends FirestoreEntity { title: string; currentVersion?: number; versions?: VersionedDocumentVersion[]; status?: PlatformStatus; visibility?: Visibility; createdBy?: string; createdAt?: DateLike; updatedAt?: DateLike; }
export interface ObjectiveTargetDocument extends FirestoreEntity { title: string; objectivePeriod?: string; targets?: Array<{ label: string; metric?: string; targetValue?: string; status?: PlatformStatus }>; currentVersion?: number; versions?: VersionedDocumentVersion[]; status?: PlatformStatus; visibility?: Visibility; createdBy?: string; createdAt?: DateLike; updatedAt?: DateLike; }
export interface CareerOpening extends FirestoreEntity { position: string; type: "Full Time" | "Part Time" | "Volunteer" | "Equity Based" | "Paid"; skills?: string[]; description?: string; closingDate?: DateLike; status?: ContentStatus; createdBy?: string; createdAt?: DateLike; }
export interface CareerApplication extends FirestoreEntity { openingId?: string; name: string; email: string; cvLink: string; sopLink?: string; expectedCompensation?: "Money" | "Equity" | "Hybrid"; createdAt?: DateLike; status?: ContentStatus; }
export interface AuditLog extends FirestoreEntity { actorId: string; action: string; collectionName: string; documentId: string; before?: unknown; after?: unknown; createdAt?: DateLike; }
export interface MsmeCase extends FirestoreEntity { title: string; category: "Digital Transformation" | "Quality" | "Manufacturing" | "Inspection" | "Reliability" | "Maintenance" | "Energy" | "Automation" | string; problem: string; solution: string; technology?: string; investment?: string; roi?: string; outcome?: string; visibility?: Visibility; createdAt?: DateLike; updatedAt?: DateLike; }
export interface Bookmark extends FirestoreEntity { userId: string; targetType: AssociatedType | "community"; targetId: string; title?: string; href?: string; createdAt?: DateLike; }
export interface CommunityAnalytics extends FirestoreEntity { postId: string; views?: number; bookmarks?: number; likes?: number; comments?: number; replies?: number; participation?: string[]; updatedAt?: DateLike; }
export interface SystemStats extends FirestoreEntity { memberCount?: number; organizationCount?: number; problemStatementCount?: number; challengeCount?: number; researchCount?: number; competitionCount?: number; knowledgeCount?: number; communityCount?: number; lastUpdated?: DateLike; }
export type PlatformModuleKey = "core" | "organizations" | "competitions" | "knowledge_hub" | "msme_intelligence" | "community" | "teams" | "admin_governance";
export interface InitializationStatus extends FirestoreEntity { initialized: boolean; version: number; modules: PlatformModuleKey[]; missingRecords: string[]; lastRunAt?: DateLike; updatedAt?: DateLike; }
export interface PlatformInitializationResult { initialized: boolean; version: number; changes: Array<{ collection: string; id: string; status: "created" | "patched" | "unchanged" }>; }
export interface SearchResult { id: string; type: string; title: string; description?: string; href: string; tags?: string[]; }
export interface OrganizationStats { organizations: number; problemStatements: number; challenges?: number; }
export interface LabelItem { id: string; label: string; sortOrder?: number; description?: string; }
export interface IndustrySector extends LabelItem { slug?: string; icon?: string; }
export interface CommunityStats { members: number; researchers: number; engineers: number; professionals: number; organizations: number; }
