"use client";
import { serverTimestamp } from "firebase/firestore";
import { useState } from "react";
import { AuthGate } from "@/components/auth-gate";
import { useAuth, useIsAdmin } from "@/components/auth-provider";
import { Card } from "@/components/ui";
import { COLLECTIONS, updateRecord, upsertRecord } from "@/lib/repositories/firestore";
function SettingsContent() { const { user, profile } = useAuth(); const isAdmin = useIsAdmin(); const [message, setMessage] = useState(""); async function saveProfile(formData: FormData) { if (!user) return; setMessage("Saving..."); try { await updateRecord(COLLECTIONS.users, user.uid, { name: String(formData.get("name") || ""), organization: String(formData.get("organization") || ""), notifications: { email: formData.get("emailNotifications") === "on", product: formData.get("productNotifications") === "on" } }); setMessage("Settings saved."); } catch (e) { setMessage(e instanceof Error ? e.message : "Unable to save settings."); } } async function savePlatform(formData: FormData) { setMessage("Saving platform settings..."); try { await upsertRecord(COLLECTIONS.settings, "platform", { maintenanceMode: formData.get("maintenanceMode") === "on", supportEmail: String(formData.get("supportEmail") || ""), updatedAt: serverTimestamp() }); setMessage("Platform settings saved."); } catch (e) { setMessage(e instanceof Error ? e.message : "Unable to save platform settings."); } } return <main className="min-h-screen bg-navy px-6 py-10"><h1 className="font-display text-5xl">Settings</h1><div className="mt-8 grid gap-6 lg:grid-cols-2"><Card><h2 className="font-display text-2xl">Profile settings</h2><form action={saveProfile} className="mt-4 grid gap-3"><input name="name" defaultValue={profile?.name || profile?.displayName || ""} placeholder="Name" className="rounded-xl border border-white/10 bg-black/30 p-3" /><input name="organization" defaultValue={(profile as { organization?: string } | null)?.organization || ""} placeholder="Organization" className="rounded-xl border border-white/10 bg-black/30 p-3" /><label className="flex gap-3 text-white/70"><input type="checkbox" name="emailNotifications" defaultChecked /> Email notifications</label><label className="flex gap-3 text-white/70"><input type="checkbox" name="productNotifications" defaultChecked /> Platform notifications</label><button className="rounded-full bg-white px-5 py-3 font-semibold text-black">Save settings</button></form></Card>{isAdmin && <Card><h2 className="font-display text-2xl">Platform settings</h2><form action={savePlatform} className="mt-4 grid gap-3"><input name="supportEmail" placeholder="Support email" className="rounded-xl border border-white/10 bg-black/30 p-3" /><label className="flex gap-3 text-white/70"><input type="checkbox" name="maintenanceMode" /> Maintenance mode</label><div className="rounded-2xl bg-white/5 p-4 text-sm text-white/60"><p>Initialization status and system status are available in the admin panel.</p></div><button className="rounded-full bg-white px-5 py-3 font-semibold text-black">Save platform settings</button></form></Card>}</div>{message && <p className="mt-4 text-white/60">{message}</p>}</main>; }
export default function Settings() { return <AuthGate><SettingsContent /></AuthGate>; }
