import type { Metadata } from "next";
export const metadata: Metadata = { title: "Knowledge & Research — NumSum Labs", description: "Approved and member-submitted research, technology intelligence, case studies, and practical knowledge for MSME problem solving." };
import { Suspense } from "react";
import { EmptyState, LoadingState } from "@/components/data-states";
import { Card } from "@/components/ui";
import { getPublicResearchItems } from "@/lib/repositories/firestore";

async function ResearchDirectory() {
  const posts = await getPublicResearchItems().catch(() => []);
  if (!posts.length) return <EmptyState message="Published and peer-reviewed research will appear here." />;
  return <div className="grid gap-4 md:grid-cols-2">{posts.map((post) => <Card key={post.id}><p className="text-xs uppercase tracking-[.2em] text-blue-300">{post.researchType || post.category || "research"}</p><h2 className="mt-2 font-display text-2xl">{post.title}</h2><p className="mt-2 text-sm text-white/60">{[post.country, post.industrySegment, post.technologyArea, post.maturityLevel].filter(Boolean).join(" · ")}</p><p className="mt-4 text-white/75">{post.summary || post.abstract}</p>{(post.practicalRelevance || post.relevanceToMSME) && <p className="mt-3 rounded-xl bg-blue-400/10 p-3 text-sm text-blue-100">Practical MSME relevance: {post.practicalRelevance || post.relevanceToMSME}</p>}<div className="mt-4 flex flex-wrap gap-2 text-sm"><span className="rounded-full bg-white/10 px-3 py-1">▲ {post.upvotes?.length || 0} upvotes</span><span className="rounded-full bg-white/10 px-3 py-1">Peer review: {post.status || "published"}</span>{post.problemStatementId && <a className="rounded-full border border-blue-300/30 px-3 py-1 text-blue-100" href={`/problem-statements/${post.problemStatementId}`}>Linked MSME challenge</a>}</div><p className="mt-3 text-sm text-white/50">Source: {post.sourceName || (post.authors || []).join(", ") || "Member submitted"}</p><div className="mt-2 flex flex-wrap gap-3 text-sm">{(post.pdf || post.documentLink || post.researchLink || post.sourceLink) && <a className="text-blue-200" href={post.pdf || post.documentLink || post.researchLink || post.sourceLink} target="_blank">Open PDF / source</a>}{post.documentLinks?.map((link, index) => <a key={link} className="text-blue-200" href={link} target="_blank">Supporting link {index + 1}</a>)}</div>{post.tags?.length ? <p className="mt-3 text-xs text-white/45">Tags: {post.tags.join(", ")}</p> : null}</Card>)}</div>;
}
export default function Research() { return <main className="min-h-screen bg-navy px-6 py-10"><section className="mx-auto max-w-7xl"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm uppercase tracking-[.3em] text-blue-300">Knowledge & Research</p><h1 className="mt-3 font-display text-5xl">Knowledge & Research</h1><p className="mt-3 max-w-3xl text-white/60">Anyone can publish their research or practical work here for admin review, peer review, and community upvotes. Keep submissions simple and include a PDF, DOI, Drive, GitHub, or source link.</p></div><a href="/research/upload" className="rounded-full bg-white px-5 py-3 font-semibold text-black">Add research</a></div><Card className="mt-6 border-blue-300/20 bg-blue-500/10"><p className="text-sm text-blue-100">Workflow: submit research → admin review → publish → peers discuss/upvote. Link the research to an MSME challenge if it solves or explains a submitted problem.</p></Card><div className="mt-8"><Suspense fallback={<LoadingState label="Loading research" />}><ResearchDirectory /></Suspense></div></section></main>; }
