import type { Metadata } from "next";
export const metadata: Metadata = { title: "MSME Intelligence — NumSum Labs", description: "Evidence-backed MSME market and technology intelligence for industrial upgradation." };
import { Card } from "@/components/ui";
import { exportOpportunities, governmentSchemes, industryClusters, industryReports, marketInsights, msmeSectors, msmeSources, stateMsmeDistribution, technologyTrends } from "@/lib/msme-intelligence-data";

function Bar({ label, value, max, suffix = "" }: { label: string; value: number; max: number; suffix?: string }) {
  return <div><div className="mb-2 flex justify-between text-sm"><span>{label}</span><span className="text-blue-300">{value}{suffix}</span></div><div className="h-3 overflow-hidden rounded-full bg-white/10"><div className="h-full rounded-full bg-blue-300" style={{ width: `${Math.max(3, (value / max) * 100)}%` }} /></div></div>;
}

export default function MsmeIntelligence() {
  const maxState = Math.max(...stateMsmeDistribution.map((s) => s.registeredMsmes));
  return <main className="min-h-screen bg-[radial-gradient(circle_at_top,#123f77_0,#02050a_44%)] px-6 py-10">
    

    <section className="mx-auto max-w-7xl py-16"><p className="text-sm uppercase tracking-[.35em] text-blue-300">MSME Intelligence</p><h1 className="mt-4 font-display text-5xl font-bold md:text-7xl">Evidence-backed MSME market intelligence</h1><p className="mt-5 max-w-3xl text-lg text-white/65">Sector, state, cluster, export and technology dashboards built from Government of India, Ministry of MSME, PIB, RAMP and IBEF references rather than placeholder data.</p><div className="mt-8 grid gap-4 md:grid-cols-4">{marketInsights.map((insight) => <Card key={insight.id}><p className="text-blue-300">{insight.metric}</p><p className="mt-3 text-white/70">{insight.insight}</p></Card>)}</div></section>

    <section className="mx-auto grid max-w-7xl gap-5 py-8 lg:grid-cols-2"><Card><h2 className="font-display text-3xl">Sector Distribution</h2><div className="mt-6 space-y-5">{msmeSectors.map((sector) => <Bar key={sector.id} label={`${sector.name} registration share`} value={sector.sharePercent} max={43} suffix="%" />)}</div><p className="mt-5 text-sm text-white/50">Source: Ministry of MSME Dashboard activity-wise registrations as on 23 June 2026.</p></Card><Card><h2 className="font-display text-3xl">State-wise MSME Distribution</h2><div className="mt-6 space-y-4">{stateMsmeDistribution.map((state) => <Bar key={state.state} label={`${state.state} (${state.region})`} value={state.registeredMsmes} max={maxState} suffix="" />)}</div><p className="mt-5 text-sm text-white/50">Registered MSME concentration view from Ministry of MSME Dashboard state-wise registrations.</p></Card></section>

    <section className="mx-auto grid max-w-7xl gap-5 py-8 lg:grid-cols-[1.1fr_.9fr]"><Card><h2 className="font-display text-3xl">Manufacturing Clusters</h2><div className="mt-6 grid gap-3 md:grid-cols-2">{industryClusters.map((cluster) => <div key={cluster.id} className="rounded-2xl border border-white/10 bg-black/20 p-4"><p className="text-blue-300">{cluster.cluster} · {cluster.state}</p><h3 className="mt-2 font-semibold">{cluster.specialization}</h3><p className="mt-2 text-sm text-white/55">{cluster.enterprises}</p></div>)}</div></Card><Card><h2 className="font-display text-3xl">Export Opportunities</h2><div className="mt-6 space-y-4">{exportOpportunities.map((item) => <div key={item.id} className="rounded-2xl bg-white/5 p-4"><p className="font-semibold text-blue-300">{item.product}</p><p className="mt-2 text-sm text-white/65">{item.opportunity}</p><p className="mt-2 text-xs text-white/45">Priority markets: {item.markets.join(", ")}</p></div>)}</div></Card></section>

    <section className="mx-auto grid max-w-7xl gap-5 py-8 lg:grid-cols-2"><Card><h2 className="font-display text-3xl">Technology Adoption</h2><div className="mt-6 space-y-5">{technologyTrends.map((trend) => <Bar key={trend.id} label={trend.trend} value={trend.maturity} max={100} suffix="" />)}</div></Card><Card><h2 className="font-display text-3xl">Government schemes and reports</h2><div className="mt-6 grid gap-3">{governmentSchemes.map((scheme) => <div key={scheme.id} className="rounded-2xl border border-white/10 p-4"><p className="font-semibold">{scheme.name}</p><p className="mt-1 text-sm text-white/60">{scheme.focus} · {scheme.agency}</p></div>)}</div><div className="mt-6"><h3 className="font-semibold text-blue-300">Industry reports collection</h3>{industryReports.map((report) => <p key={report.id} className="mt-2 text-sm text-white/60">{report.year}: {report.title} — {report.publisher}</p>)}</div></Card></section>

    <section className="mx-auto max-w-7xl py-8"><Card><h2 className="font-display text-3xl">Firestore collections to seed</h2><div className="mt-5 flex flex-wrap gap-2">{["industry_clusters","msme_sectors","government_schemes","export_opportunities","industry_reports","market_insights","technology_trends"].map((name) => <code key={name} className="rounded-full bg-white/10 px-3 py-2 text-sm text-blue-100">{name}</code>)}</div><h3 className="mt-7 font-semibold text-blue-300">Data sources</h3><div className="mt-3 grid gap-2 md:grid-cols-2">{msmeSources.map((source) => <a key={source.url} href={source.url} className="text-sm text-white/60 underline decoration-white/20 hover:text-white">{source.title}</a>)}</div></Card></section>
  </main>;
}
